#!groovy
pipeline {
  agent any
  stages {
      stage('Verif') {
           steps {
                sh 'whoami'
           }
      }

    stage('Maven Install') {
    	    agent {
          	docker {
            	image 'maven:3.5.0'
            }
          }

          steps {
          	sh 'mvn clean install'
          }
      
    }

    stage('Docker Build') {
      agent any
      steps {
        sh 'docker build -t tarek/spring-petclinic:latest .'
      }
    }
  }
}
